apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "articles-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "articles-api.name" . }}
    helm.sh/chart: {{ include "articles-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "articles-api.name" . }}-job
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - name: api-config
        configMap:
          name: {{ .Release.Name }}-configmap
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["./articles",  "migrate", "up"]
        volumeMounts:
        - name: api-config
          mountPath: /app/config
        workingDir: /app
      restartPolicy: Never
  backoffLimit: 1