apiVersion: v1
kind: Service
metadata:
  name: {{ include "articles-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "articles-api.name" . }}
    helm.sh/chart: {{ include "articles-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 9080
      protocol: TCP
      name: apihttp
    - port: {{ .Values.service.swaggerui.port }}
      targetPort: 8080
      protocol: TCP
      name: swaggerhttp
  selector:
    app.kubernetes.io/name: {{ include "articles-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
